"""
Prism Alert Service — Creates Alerts in Prometheus and Datadog.

Provides async methods to:
1. Generate Prometheus alert rule YAML files and optionally commit them
   to the PR branch via GitHub API.
2. Create Datadog monitors via the Datadog API.
"""

import json
import re
from typing import Any

import httpx
from observability.logging import get_logger
from utils.config import settings

logger = get_logger(__name__)

def _normalize_filename(name: str) -> str:
    """Convert a name into a safe filename (lowercase, hyphens, no special chars)."""
    name = name.lower().strip()
    name = re.sub(r"[^a-z0-9\s-]", "", name)
    name = re.sub(r"[\s]+", "-", name)
    return name

def _build_prometheus_alert_rule(suggestion: dict[str, Any]) -> str:
    """
    Build a Prometheus alert rule YAML string from an AlertSuggestion.

    """
    name = suggestion.get("name", "unnamed-alert")
    query = suggestion.get("query", "up == 0")
    duration = suggestion.get("duration", "5m")
    priority = suggestion.get("priority", "P1")
    description = suggestion.get("description", "")
    runbook = suggestion.get("runbook_link", "")
    notification = suggestion.get("notification", "")

    severity_map = {"P0": "critical", "P1": "warning", "P2": "info"}
    severity = severity_map.get(priority, "warning")

    rule_yaml = f"""# Auto-generated by Prism AI Code Reviewer
groups:
  - name: prism-generated-alerts
    rules:
      - alert: {name.replace(' ', '')}
        expr: {query}
        for: {duration}
        labels:
          severity: {severity}
          source: prism
          priority: {priority}
        annotations:
          summary: "{name}"
          description: "{description}"
          runbook_url: "{runbook}"
          notification_channel: "{notification}"
"""
    return rule_yaml

class AlertService:
    """Creates alerts in Prometheus and Datadog."""

    # ── Prometheus ────────────────────────────────────────────────────────

    async def create_prometheus_alert(
        self,
        suggestion: dict[str, Any],
        repo_full_name: str | None = None,
        pr_branch: str | None = None,
    ) -> dict:
        """
        Create a Prometheus alert rule.

        In CI mode (when repo_full_name and pr_branch are provided), commits
        the YAML file directly to the PR branch via GitHub API.
        Otherwise, returns the YAML content for manual application.
        """
        name = suggestion.get("name", "unnamed-alert")
        alert_yaml = _build_prometheus_alert_rule(suggestion)
        filename = f"{_normalize_filename(name)}.yml"

        # If running in CI with repo context, commit to the repository
        if repo_full_name and pr_branch:
            return await self._commit_alert_to_repo(
                repo_full_name=repo_full_name,
                branch=pr_branch,
                filepath=f"monitoring/prometheus/rules/{filename}",
                content=alert_yaml,
                alert_name=name,
            )

        # Otherwise return the YAML for manual application
        logger.info("prometheus_alert_generated", name=name, filename=filename)
        return {
            "status": "generated",
            "name": name,
            "filename": filename,
            "content": alert_yaml,
            "message": f"Prometheus alert rule generated. Apply with: kubectl apply -f {filename}",
        }

    async def _commit_alert_to_repo(
        self,
        repo_full_name: str,
        branch: str,
        filepath: str,
        content: str,
        alert_name: str,
    ) -> dict:
        """
        Commit an alert rule YAML file directly to the PR branch via GitHub API.

        """
        import base64

        token = settings.github_token
        if not token:
            return {"error": "GitHub token not configured for commit"}

        url = f"https://api.github.com/repos/{repo_full_name}/contents/{filepath}"
        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        # Check if file already exists (to get its SHA for updates)
        sha = None
        async with httpx.AsyncClient(timeout=30) as client:
            existing = await client.get(f"{url}?ref={branch}", headers=headers)
            if existing.status_code == 200:
                sha = existing.json().get("sha")

        # Commit the file
        payload: dict[str, Any] = {
            "message": f"feat(alerts): add Prometheus alert rule for {alert_name}\n\nAuto-generated by Prism AI Code Reviewer",
            "content": base64.b64encode(content.encode()).decode(),
            "branch": branch,
        }
        if sha:
            payload["sha"] = sha

        async with httpx.AsyncClient(timeout=30) as client:
            try:
                response = await client.put(url, json=payload, headers=headers)
                if response.status_code < 200 or response.status_code > 299:
                    logger.error(
                        "github_commit_alert_failed",
                        status=response.status_code,
                        body=response.text[:300],
                    )
                    return {"error": f"GitHub API error ({response.status_code}): {response.text[:200]}"}
                logger.info("prometheus_alert_committed", name=alert_name, path=filepath)
                return {
                    "status": "committed",
                    "name": alert_name,
                    "path": filepath,
                    "sha": response.json().get("content", {}).get("sha", ""),
                }
            except Exception as e:
                logger.error("github_commit_alert_error", error=str(e))
                return {"error": str(e)}

    # ── Datadog ───────────────────────────────────────────────────────────

    async def create_datadog_alert(self, suggestion: dict[str, Any]) -> dict:
        """
        Create a Datadog monitor via the Datadog API.

        """
        dd_api_key = settings.datadog_api_key
        dd_app_key = settings.datadog_app_key

        if not dd_api_key or not dd_app_key:
            logger.error("datadog_alerts_not_configured")
            return {"error": "Datadog API key or App key not configured"}

        name = suggestion.get("name", "Unnamed Alert")
        query = suggestion.get("query", "")
        description = suggestion.get("description", "")
        priority = suggestion.get("priority", "P1")

        if not query:
            return {"error": f"No query provided for alert: {name}"}

        # Convert PromQL-style query to Datadog format if needed
        dd_query = self._convert_to_datadog_query(query)

        monitor_body = {
            "name": name,
            "type": "log alert",
            "query": dd_query,
            "message": f"{name}\n\nDescription: {description}\nPriority: {priority}",
            "options": {
                "notify_no_data": False,
                "require_full_window": False,
                "timeout_h": 0,
            },
        }

        dd_host = settings.datadog_host or "api.datadoghq.com"
        url = f"https://{dd_host}/api/v1/monitor"
        headers = {
            "Content-Type": "application/json",
            "DD-API-KEY": dd_api_key,
            "DD-APPLICATION-KEY": dd_app_key,
        }

        async with httpx.AsyncClient(timeout=30) as client:
            try:
                response = await client.post(url, json=monitor_body, headers=headers)
                if response.status_code < 200 or response.status_code > 299:
                    logger.error(
                        "datadog_monitor_api_error",
                        status=response.status_code,
                        body=response.text[:500],
                    )
                    return {"error": f"Datadog API error ({response.status_code}): {response.text[:200]}"}
                result = response.json()
                logger.info("datadog_monitor_created", name=name, monitor_id=result.get("id"))
                return {"status": "created", "name": name, "monitor_id": result.get("id")}
            except Exception as e:
                logger.error("datadog_monitor_request_error", error=str(e))
                return {"error": str(e)}

    @staticmethod
    def _convert_to_datadog_query(query: str) -> str:
        """
        Basic conversion from PromQL to Datadog query format.

        This handles simple cases; complex queries may need manual adjustment.
        """
        # If it already looks like a Datadog query, return as-is
        if "logs(" in query or "avg:" in query or "sum:" in query:
            return query

        # Simple count pattern: count(message=~"...") > N
        count_match = re.search(r'count\(message=~"([^"]+)"\)\s*>\s*([\d.]+)', query)
        if count_match:
            message_pattern = count_match.group(1).replace(".*", "*")
            threshold = count_match.group(2)
            return f'logs("message:~\\"{message_pattern}\\"").index("*").rollup("count").last("5m") > {threshold}'

        # Fallback: wrap as a generic logs query
        # Extract threshold if present
        threshold_match = re.search(r">\s*([\d.]+)", query)
        threshold = threshold_match.group(1) if threshold_match else "1.0"
        return f'logs("*").index("*").rollup("count").last("5m") > {threshold}'

    # ── Router ────────────────────────────────────────────────────────────

    async def create_alert(
        self,
        suggestion: dict[str, Any],
        repo_full_name: str | None = None,
        pr_branch: str | None = None,
    ) -> dict:
        """Route an alert suggestion to the correct platform."""
        alert_type = suggestion.get("type", "prometheus").lower()

        if alert_type == "prometheus":
            return await self.create_prometheus_alert(suggestion, repo_full_name, pr_branch)
        elif alert_type == "datadog":
            return await self.create_datadog_alert(suggestion)
        else:
            logger.warning("unknown_alert_type", type=alert_type)
            return {"error": f"Unknown alert type: {alert_type}"}
